---
abstract: 'App::Nopaste service for www.pastebin.ca'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Nopaste-Service-PastebinCa
requires:
  App::Nopaste::Service: 0
  WWW::Pastebin::PastebinCa::Create: 0
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/zoffixznet/App-Nopaste-Service-PastebinCa/issues
  repository: git://github.com/zoffixznet/App-Nopaste-Service-PastebinCa.git
version: 1.004
